### PR TITLE
doc2wiki using wiki slice and ES

### PR DESCRIPTION
**Pull request by keighrim**
To address brandeis-llc/dtriac-wikification#2, the wikification is implemented via brandeis-llc/dtriac-wikification#10, and this PR integrates that into pipeline.

### CODE REVIEW

**Comment by keighrim** [comment]
Wikified LIF is being generated in `/data/dtriac/dtriac-19d/all-processed/wik` on `tarski`, ETA is about 40 minutes from now.

**Comment by keighrim** [comment]
`wik` files are all generated. Next we need to insert those wiki titles into ES index file.

**Comment by keighrim** [comment]
wikification code (https://github.com/brandeis-llc/dtriac-wikification/pull/10) returns up to 10 matches, and 93eb073 adds all of those to `ground_more` field. We can decide how much of the list we want to incude.  @marcverhagen any idea?

**Comment by marcverhagen** [comment]
@keighrim I was just going to do trial and error, starting with using 5 of them. Question: do you just pick the first 10 or do you also use some threshold value (this is assuming you have some score to work with).

**Comment by keighrim** [comment]
10 was a completely arbitrary number I picked at my discretion. I can add scores to each title as well. I take \~50 minutes for performing ES search for 15k documents.

**Comment by marcverhagen** [comment]
10 is a fine number, I was just thinking that if some of them have a low score we should perhaps not include them.

**Comment by keighrim** [comment]
https://github.com/brandeis-llc/dtriac-wikification/pull/12 implements scores attached to titles. The value is now a list of dicts of two keys `title` and `score`.

**Comment by keighrim** [comment]
I'm running wikification with score now, and looking at the scores. They are very high and vary a lot, (\~300 - \~20000). If you want to use some threshold, it should be some relative percentage of the top score for each document.

**Pull request merged**
